# Generated by Django 5.2.6 on 2025-09-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='no_of_items',
        ),
        migrations.AddField(
            model_name='category',
            name='no_of_items_available_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
    ]
