# Generated by Django 5.2.6 on 2025-09-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_no_of_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pic_url',
            field=models.ImageField(upload_to='store/static/store/images/'),
        ),
    ]
