# Generated by Django 5.2.6 on 2025-09-29 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_pic_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/store/images/category_pics'),
            preserve_default=False,
        ),
    ]
