# Generated by Django 5.2.6 on 2025-09-30 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous User', max_length=200)),
                ('pic', models.ImageField(upload_to='store/images/users')),
                ('review', models.TextField(max_length=400)),
                ('date', models.DateField(verbose_name=datetime.datetime.utcnow)),
            ],
        ),
    ]
