# Generated by Django 5.2.6 on 2025-10-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='review',
            name='pic',
        ),
    ]
