# Generated by Django 5.2.6 on 2025-10-01 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_name_review_username_remove_review_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
